version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  except:
  - ci/travis
skip_commits:
  message: /Merge tag.*into develop/
  files:
    - '*.md'
    - LICENSE
    - .travis.yml
image: Visual Studio 2017
cache: tools -> setup.cake,tools/packages.config,.appveyor.yml
install:
- cinst transifex-client --version 0.12.4
build_script:
- ps: .\build.ps1 -Configuration Release -Target AppVeyor
test: off
deploy: off
